### ISSUE TITLE
Is this project complete?

### ISSUE THREAD

**Issue by aarongustafson** [iorikay/Contact10kApart#1]
I get nothing in the browser.

**Comment by iorikay** [comment]
Hello, 
No my project is not complete yet.
But I swear it deserve a chance to be fullfilled.
However, I've added an index page to show the progress.
From now on you can list and view contacts.
With the magic of javascript and XSL parameters, sorting and searching will come soon.

**Comment by aarongustafson** [comment]
Unfortunately as it wasn’t complete by the time the contest closed, I’m going to have to reject the entry. I’m sorry, but it’s the only way to be fair to all of the people who completed their projects before the deadline.
